version: "3"
services:
  krakend:
    image: devopsfaith/krakend
    volumes:
      - .:/etc/krakend
    ports:
      - "8080:8080"
    environment:
      - FC_ENABLE=1
      - FC_SETTINGS=config/settings/prod
      - FC_PARTIALS=config/partials
      - FC_TEMPLATES=config/templates
      - FC_OUT=krakend.json
      - SERVICE_NAME=Infratographer API Gateway
    command: [ "run", "-dc", "krakend.tmpl", "" ]
